"""pulse ritual schema

Revision ID: 18fc1fbd1eec
Revises: 2eda314919aa
Create Date: 2026-08-07 11:39:11.354429

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "18fc1fbd1eec"
down_revision: str | Sequence[str] | None = "2eda314919aa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "commitments",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("owner_user_id", sa.String(), nullable=False),
        sa.Column("promised_to_person_id", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("source_reference_key", sa.String(), nullable=False),
        sa.Column("promised_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_commitments_owner_user_id"),
        "commitments",
        ["owner_user_id"],
        unique=False,
    )
    op.create_table(
        "goals",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("owner_user_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("external_ref", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_goals_owner_user_id"), "goals", ["owner_user_id"], unique=False
    )
    op.create_table(
        "pulse_deliveries",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("owner_user_id", sa.String(), nullable=False),
        sa.Column("ritual", sa.String(), nullable=False),
        sa.Column("local_date", sa.Date(), nullable=False),
        sa.Column("trigger", sa.String(), nullable=False),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("item_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("context_hash", sa.String(), nullable=False),
        sa.Column("prompt_version", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "owner_user_id",
            "ritual",
            "local_date",
            "trigger",
            name="uq_pulse_delivery_owner_ritual_date_trigger",
        ),
    )
    op.create_index(
        op.f("ix_pulse_deliveries_owner_user_id"),
        "pulse_deliveries",
        ["owner_user_id"],
        unique=False,
    )
    op.create_table(
        "raw_ingest_refs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("owner_user_id", sa.String(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("external_id", sa.String(), nullable=True),
        sa.Column("canonical_table", sa.String(), nullable=False),
        sa.Column("canonical_id", sa.String(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("checksum", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_raw_ingest_refs_owner_user_id"),
        "raw_ingest_refs",
        ["owner_user_id"],
        unique=False,
    )
    op.create_table(
        "suppressions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("owner_user_id", sa.String(), nullable=False),
        sa.Column("scope", sa.String(), nullable=False),
        sa.Column("target_ref", sa.String(), nullable=False),
        sa.Column("reason", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_suppressions_owner_user_id"),
        "suppressions",
        ["owner_user_id"],
        unique=False,
    )
    op.create_table(
        "weights",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("owner_user_id", sa.String(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_user_id", "key", name="uq_weight_owner_key"),
    )
    op.create_index(
        op.f("ix_weights_owner_user_id"), "weights", ["owner_user_id"], unique=False
    )
    op.create_table(
        "feedback_events",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("owner_user_id", sa.String(), nullable=False),
        sa.Column("pulse_delivery_id", sa.String(), nullable=False),
        sa.Column("item_id", sa.String(), nullable=False),
        sa.Column("signal", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pulse_delivery_id"],
            ["pulse_deliveries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_feedback_events_owner_user_id"),
        "feedback_events",
        ["owner_user_id"],
        unique=False,
    )
    op.add_column("events", sa.Column("source", sa.String(), nullable=True))
    op.add_column("events", sa.Column("external_id", sa.String(), nullable=True))
    op.add_column("events", sa.Column("title", sa.String(), nullable=True))
    op.add_column(
        "events", sa.Column("starts_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "events", sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("events", sa.Column("status", sa.String(), nullable=True))
    op.add_column("events", sa.Column("url", sa.String(), nullable=True))
    op.add_column("events", sa.Column("series_id", sa.String(), nullable=True))
    op.create_index(
        "uq_event_owner_source_external_id",
        "events",
        ["owner_user_id", "source", "external_id"],
        unique=True,
        sqlite_where=sa.text("external_id IS NOT NULL"),
        postgresql_where=sa.text("external_id IS NOT NULL"),
    )
    op.add_column("messages", sa.Column("source", sa.String(), nullable=True))
    op.add_column("messages", sa.Column("external_id", sa.String(), nullable=True))
    op.add_column("messages", sa.Column("channel", sa.String(), nullable=True))
    op.add_column(
        "messages", sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("messages", sa.Column("url", sa.String(), nullable=True))
    op.add_column("messages", sa.Column("is_dm", sa.Boolean(), nullable=False))
    op.add_column("messages", sa.Column("body_ref", sa.String(), nullable=True))
    op.create_index(
        "uq_message_owner_source_external_id",
        "messages",
        ["owner_user_id", "source", "external_id"],
        unique=True,
        sqlite_where=sa.text("external_id IS NOT NULL"),
        postgresql_where=sa.text("external_id IS NOT NULL"),
    )
    op.add_column("users", sa.Column("tz", sa.String(), nullable=False))
    op.add_column(
        "users", sa.Column("pulse_fire_time_local", sa.Time(), nullable=False)
    )
    op.add_column("users", sa.Column("late_cutoff_local", sa.Time(), nullable=False))
    op.add_column("work_items", sa.Column("source", sa.String(), nullable=True))
    op.add_column("work_items", sa.Column("external_id", sa.String(), nullable=True))
    op.add_column("work_items", sa.Column("title", sa.String(), nullable=True))
    op.add_column("work_items", sa.Column("status", sa.String(), nullable=True))
    op.add_column("work_items", sa.Column("url", sa.String(), nullable=True))
    op.add_column(
        "work_items", sa.Column("due_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "work_items", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.create_index(
        "uq_work_item_owner_source_external_id",
        "work_items",
        ["owner_user_id", "source", "external_id"],
        unique=True,
        sqlite_where=sa.text("external_id IS NOT NULL"),
        postgresql_where=sa.text("external_id IS NOT NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_work_item_owner_source_external_id",
        table_name="work_items",
        sqlite_where=sa.text("external_id IS NOT NULL"),
        postgresql_where=sa.text("external_id IS NOT NULL"),
    )
    op.drop_column("work_items", "updated_at")
    op.drop_column("work_items", "due_at")
    op.drop_column("work_items", "url")
    op.drop_column("work_items", "status")
    op.drop_column("work_items", "title")
    op.drop_column("work_items", "external_id")
    op.drop_column("work_items", "source")
    op.drop_column("users", "late_cutoff_local")
    op.drop_column("users", "pulse_fire_time_local")
    op.drop_column("users", "tz")
    op.drop_index(
        "uq_message_owner_source_external_id",
        table_name="messages",
        sqlite_where=sa.text("external_id IS NOT NULL"),
        postgresql_where=sa.text("external_id IS NOT NULL"),
    )
    op.drop_column("messages", "body_ref")
    op.drop_column("messages", "is_dm")
    op.drop_column("messages", "url")
    op.drop_column("messages", "sent_at")
    op.drop_column("messages", "channel")
    op.drop_column("messages", "external_id")
    op.drop_column("messages", "source")
    op.drop_index(
        "uq_event_owner_source_external_id",
        table_name="events",
        sqlite_where=sa.text("external_id IS NOT NULL"),
        postgresql_where=sa.text("external_id IS NOT NULL"),
    )
    op.drop_column("events", "series_id")
    op.drop_column("events", "url")
    op.drop_column("events", "status")
    op.drop_column("events", "ends_at")
    op.drop_column("events", "starts_at")
    op.drop_column("events", "title")
    op.drop_column("events", "external_id")
    op.drop_column("events", "source")
    op.drop_index(
        op.f("ix_feedback_events_owner_user_id"), table_name="feedback_events"
    )
    op.drop_table("feedback_events")
    op.drop_index(op.f("ix_weights_owner_user_id"), table_name="weights")
    op.drop_table("weights")
    op.drop_index(op.f("ix_suppressions_owner_user_id"), table_name="suppressions")
    op.drop_table("suppressions")
    op.drop_index(
        op.f("ix_raw_ingest_refs_owner_user_id"), table_name="raw_ingest_refs"
    )
    op.drop_table("raw_ingest_refs")
    op.drop_index(
        op.f("ix_pulse_deliveries_owner_user_id"), table_name="pulse_deliveries"
    )
    op.drop_table("pulse_deliveries")
    op.drop_index(op.f("ix_goals_owner_user_id"), table_name="goals")
    op.drop_table("goals")
    op.drop_index(op.f("ix_commitments_owner_user_id"), table_name="commitments")
    op.drop_table("commitments")
    # ### end Alembic commands ###
