"""initial owner-scoped schema

Revision ID: 2eda314919aa
Revises:
Create Date: 2026-08-06 09:54:52.494361

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2eda314919aa"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "events",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("owner_user_id", sa.String(), nullable=False),
        sa.Column("actor_reference_key", sa.String(), nullable=False),
        sa.Column("resolved_person_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_events_actor_reference_key"),
        "events",
        ["actor_reference_key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_events_owner_user_id"), "events", ["owner_user_id"], unique=False
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("owner_user_id", sa.String(), nullable=False),
        sa.Column("actor_reference_key", sa.String(), nullable=False),
        sa.Column("resolved_person_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_messages_actor_reference_key"),
        "messages",
        ["actor_reference_key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_messages_owner_user_id"), "messages", ["owner_user_id"], unique=False
    )
    op.create_table(
        "persons",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("owner_user_id", sa.String(), nullable=False),
        sa.Column("canonical_name", sa.String(), nullable=False),
        sa.Column("primary_email", sa.String(), nullable=True),
        sa.Column("is_self", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("roster_source", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_person_owner", "persons", ["owner_user_id"], unique=False)
    op.create_index(
        "uq_person_owner_primary_email",
        "persons",
        ["owner_user_id", "primary_email"],
        unique=True,
        sqlite_where=sa.text("primary_email IS NOT NULL"),
        postgresql_where=sa.text("primary_email IS NOT NULL"),
    )
    op.create_table(
        "roster_version",
        sa.Column("owner_user_id", sa.String(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("owner_user_id"),
    )
    op.create_table(
        "unresolved_references",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("owner_user_id", sa.String(), nullable=False),
        sa.Column("reference_key", sa.String(), nullable=False),
        sa.Column("key_version", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("external_id", sa.String(), nullable=True),
        sa.Column("handle", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("display_name", sa.String(), nullable=True),
        sa.Column(
            "candidates", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("best_score", sa.Float(), nullable=True),
        sa.Column("margin", sa.Float(), nullable=True),
        sa.Column("occurrence_count", sa.Integer(), nullable=False),
        sa.Column("distinct_day_count", sa.Integer(), nullable=False),
        sa.Column("last_seen_date", sa.Date(), nullable=True),
        sa.Column("ask_count", sa.Integer(), nullable=False),
        sa.Column("scored_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("roster_version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("first_seen", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "owner_user_id", "reference_key", name="uq_unresolved_owner_reference_key"
        ),
    )
    op.create_index(
        "ix_unresolved_reference_owner",
        "unresolved_references",
        ["owner_user_id"],
        unique=False,
    )
    op.create_table(
        "work_items",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("owner_user_id", sa.String(), nullable=False),
        sa.Column("actor_reference_key", sa.String(), nullable=False),
        sa.Column("resolved_person_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_work_items_actor_reference_key"),
        "work_items",
        ["actor_reference_key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_work_items_owner_user_id"),
        "work_items",
        ["owner_user_id"],
        unique=False,
    )
    op.create_table(
        "identities",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("owner_user_id", sa.String(), nullable=False),
        sa.Column("person_id", sa.String(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("external_id", sa.String(), nullable=True),
        sa.Column("reference_key", sa.String(), nullable=False),
        sa.Column("key_version", sa.Integer(), nullable=False),
        sa.Column("tier", sa.Integer(), nullable=False),
        sa.Column("confidence", sa.String(), nullable=False),
        sa.Column("verified_by", sa.String(), nullable=False),
        sa.Column("handle", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("display_name", sa.String(), nullable=True),
        sa.Column(
            "provenance", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("first_seen", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["persons.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "owner_user_id", "reference_key", name="uq_identity_owner_reference_key"
        ),
    )
    op.create_index("ix_identity_owner", "identities", ["owner_user_id"], unique=False)
    op.create_index(
        "uq_identity_owner_source_external_id",
        "identities",
        ["owner_user_id", "source", "external_id"],
        unique=True,
        sqlite_where=sa.text("external_id IS NOT NULL"),
        postgresql_where=sa.text("external_id IS NOT NULL"),
    )
    op.create_table(
        "merge_log",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("owner_user_id", sa.String(), nullable=False),
        sa.Column("person_id", sa.String(), nullable=False),
        sa.Column("reference_key", sa.String(), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("prev_person_id", sa.String(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tier", sa.Integer(), nullable=True),
        sa.Column("confidence", sa.String(), nullable=True),
        sa.Column("actor", sa.String(), nullable=False),
        sa.Column("reason", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["persons.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_merge_log_owner", "merge_log", ["owner_user_id"], unique=False)
    op.create_index(
        op.f("ix_merge_log_reference_key"), "merge_log", ["reference_key"], unique=False
    )
    op.create_table(
        "not_same_as",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("owner_user_id", sa.String(), nullable=False),
        sa.Column("reference_key", sa.String(), nullable=False),
        sa.Column("person_id", sa.String(), nullable=False),
        sa.Column("rejected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["persons.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_not_same_as_owner_key_person",
        "not_same_as",
        ["owner_user_id", "reference_key", "person_id"],
        unique=False,
    )
    op.create_table(
        "pending_confirmations",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("owner_user_id", sa.String(), nullable=False),
        sa.Column("reference_key", sa.String(), nullable=False),
        sa.Column("candidate_person_id", sa.String(), nullable=False),
        sa.Column("candidate_score", sa.Float(), nullable=False),
        sa.Column("surface", sa.String(), nullable=False),
        sa.Column("card_ref", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("asked_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("answered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["candidate_person_id"],
            ["persons.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_pending_confirmation_owner",
        "pending_confirmations",
        ["owner_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pending_confirmations_reference_key"),
        "pending_confirmations",
        ["reference_key"],
        unique=False,
    )
    op.create_index(
        "uq_pending_confirmation_owner_key_candidate",
        "pending_confirmations",
        ["owner_user_id", "reference_key", "candidate_person_id"],
        unique=True,
        sqlite_where=sa.text("status = 'pending'"),
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.create_table(
        "person_relationships",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("owner_user_id", sa.String(), nullable=False),
        sa.Column("person_id_a", sa.String(), nullable=False),
        sa.Column("person_id_b", sa.String(), nullable=False),
        sa.Column("co_meeting_count", sa.Integer(), nullable=False),
        sa.Column("shared_project_count", sa.Integer(), nullable=False),
        sa.Column("last_contact_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["person_id_a"],
            ["persons.id"],
        ),
        sa.ForeignKeyConstraint(
            ["person_id_b"],
            ["persons.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "owner_user_id",
            "person_id_a",
            "person_id_b",
            name="uq_person_relationship_owner_pair",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("person_relationships")
    op.drop_index(
        "uq_pending_confirmation_owner_key_candidate",
        table_name="pending_confirmations",
        sqlite_where=sa.text("status = 'pending'"),
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.drop_index(
        op.f("ix_pending_confirmations_reference_key"),
        table_name="pending_confirmations",
    )
    op.drop_index("ix_pending_confirmation_owner", table_name="pending_confirmations")
    op.drop_table("pending_confirmations")
    op.drop_index("ix_not_same_as_owner_key_person", table_name="not_same_as")
    op.drop_table("not_same_as")
    op.drop_index(op.f("ix_merge_log_reference_key"), table_name="merge_log")
    op.drop_index("ix_merge_log_owner", table_name="merge_log")
    op.drop_table("merge_log")
    op.drop_index(
        "uq_identity_owner_source_external_id",
        table_name="identities",
        sqlite_where=sa.text("external_id IS NOT NULL"),
        postgresql_where=sa.text("external_id IS NOT NULL"),
    )
    op.drop_index("ix_identity_owner", table_name="identities")
    op.drop_table("identities")
    op.drop_index(op.f("ix_work_items_owner_user_id"), table_name="work_items")
    op.drop_index(op.f("ix_work_items_actor_reference_key"), table_name="work_items")
    op.drop_table("work_items")
    op.drop_index("ix_unresolved_reference_owner", table_name="unresolved_references")
    op.drop_table("unresolved_references")
    op.drop_table("roster_version")
    op.drop_index(
        "uq_person_owner_primary_email",
        table_name="persons",
        sqlite_where=sa.text("primary_email IS NOT NULL"),
        postgresql_where=sa.text("primary_email IS NOT NULL"),
    )
    op.drop_index("ix_person_owner", table_name="persons")
    op.drop_table("persons")
    op.drop_index(op.f("ix_messages_owner_user_id"), table_name="messages")
    op.drop_index(op.f("ix_messages_actor_reference_key"), table_name="messages")
    op.drop_table("messages")
    op.drop_index(op.f("ix_events_owner_user_id"), table_name="events")
    op.drop_index(op.f("ix_events_actor_reference_key"), table_name="events")
    op.drop_table("events")
    op.drop_table("users")
    # ### end Alembic commands ###
