"""rolling agenda schema

Revision ID: 789abc1406de
Revises: 4a6ca370c3be
Create Date: 2026-08-14 16:50:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "789abc1406de"
down_revision: str | Sequence[str] | None = "4a6ca370c3be"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("hris_employee_id", sa.String(), nullable=True))
    op.create_unique_constraint(
        "uq_users_hris_employee_id", "users", ["hris_employee_id"]
    )

    op.create_table(
        "pairs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("report_user_id", sa.String(), nullable=False),
        sa.Column("manager_user_id", sa.String(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["manager_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["report_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_pair_report", "pairs", ["report_user_id"], unique=False)
    op.create_index(
        "uq_pair_one_active_per_report",
        "pairs",
        ["report_user_id"],
        unique=True,
        sqlite_where=sa.text("ended_at IS NULL"),
        postgresql_where=sa.text("ended_at IS NULL"),
    )

    op.create_table(
        "agenda_items",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("report_user_id", sa.String(), nullable=False),
        sa.Column("pair_id", sa.String(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("source_link", sa.String(), nullable=True),
        sa.Column("visibility", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("surfaced_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_user_id", sa.String(), nullable=False),
        sa.Column("created_by_role", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pair_id"],
            ["pairs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["report_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_agenda_item_report", "agenda_items", ["report_user_id"], unique=False
    )
    op.create_index(
        "uq_agenda_item_report_source_link",
        "agenda_items",
        ["report_user_id", "source_link"],
        unique=True,
        sqlite_where=sa.text("source_link IS NOT NULL AND status != 'resolved'"),
        postgresql_where=sa.text("source_link IS NOT NULL AND status != 'resolved'"),
    )

    op.create_table(
        "agenda_item_history",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("agenda_item_id", sa.String(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("changed_by_user_id", sa.String(), nullable=False),
        sa.Column("changed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("diff", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["agenda_item_id"],
            ["agenda_items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["changed_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_agenda_item_history_item",
        "agenda_item_history",
        ["agenda_item_id"],
        unique=False,
    )

    op.create_table(
        "accomplishments",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("owner_user_id", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("source_reference_key", sa.String(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("accomplishments")
    op.drop_index("ix_agenda_item_history_item", table_name="agenda_item_history")
    op.drop_table("agenda_item_history")
    op.drop_index("uq_agenda_item_report_source_link", table_name="agenda_items")
    op.drop_index("ix_agenda_item_report", table_name="agenda_items")
    op.drop_table("agenda_items")
    op.drop_index("uq_pair_one_active_per_report", table_name="pairs")
    op.drop_index("ix_pair_report", table_name="pairs")
    op.drop_table("pairs")
    op.drop_constraint("uq_users_hris_employee_id", "users", type_="unique")
    op.drop_column("users", "hris_employee_id")
    # ### end Alembic commands ###
