"""add okr columns to goals and one_on_one_notes table

Revision ID: b0854c783433
Revises: c556b944a1bb
Create Date: 2026-08-17 18:30:00.000000

Adds User.notion_owner_email (link-notion CLI step, resolves this user's
Notion "person" identity by email — needed since Career Goals/Key Results
have no Owner field of their own, confirmed live; ownership is resolved
transitively through Objectives' Owner instead).

Adds real ingestion-shape columns to Goal (source/external_id for
idempotent upsert keying + RawIngestRef provenance, matching Event/
WorkItem/Message's existing convention; goal_type to distinguish
objective/key_result/career_goal — the "quarterly OKR" vs "career growth
goal" distinction, solved structurally via Notion's separate databases;
parent_external_id for the KR->Objective/Objective->CareerGoal hierarchy;
quarter/progress/current_value/target_value for OKR display). Also adds
a new one_on_one_notes table for Notion's private "1:1 Notes" db content
— kept separate from Goal rather than overloaded into it, since a
meeting note is not a goal.

Hand-written (not autogenerated): no live DB was reachable in the
environment this was authored in (Docker Desktop not running locally) to
run `alembic revision --autogenerate` against. Columns/table match
app/core/models.py's Goal/OneOnOneNote definitions exactly; review this
migration against a real `alembic upgrade head` run before merging.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b0854c783433"
down_revision: str | Sequence[str] | None = "c556b944a1bb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "users", sa.Column("notion_owner_email", sa.String(), nullable=True)
    )
    op.create_unique_constraint(
        "uq_users_notion_owner_email", "users", ["notion_owner_email"]
    )
    op.add_column("goals", sa.Column("source", sa.String(), nullable=True))
    op.add_column("goals", sa.Column("external_id", sa.String(), nullable=True))
    op.add_column(
        "goals",
        sa.Column(
            "goal_type", sa.String(), nullable=False, server_default="objective"
        ),
    )
    op.alter_column("goals", "goal_type", server_default=None)
    op.add_column(
        "goals", sa.Column("parent_external_id", sa.String(), nullable=True)
    )
    op.add_column("goals", sa.Column("quarter", sa.String(), nullable=True))
    op.add_column("goals", sa.Column("progress", sa.Float(), nullable=True))
    op.add_column("goals", sa.Column("current_value", sa.Float(), nullable=True))
    op.add_column("goals", sa.Column("target_value", sa.Float(), nullable=True))
    op.create_index(
        "uq_goal_owner_source_external_id",
        "goals",
        ["owner_user_id", "source", "external_id"],
        unique=True,
        postgresql_where=sa.text("external_id IS NOT NULL"),
    )

    op.create_table(
        "one_on_one_notes",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("owner_user_id", sa.String(), nullable=False),
        sa.Column("source", sa.String(), nullable=True),
        sa.Column("external_id", sa.String(), nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("meeting_id", sa.String(), nullable=True),
        sa.Column("linked_key_result_external_ids", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["owner_user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_one_on_one_notes_owner_user_id"),
        "one_on_one_notes",
        ["owner_user_id"],
    )
    op.create_index(
        "uq_one_on_one_note_owner_source_external_id",
        "one_on_one_notes",
        ["owner_user_id", "source", "external_id"],
        unique=True,
        postgresql_where=sa.text("external_id IS NOT NULL"),
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(
        "uq_one_on_one_note_owner_source_external_id",
        table_name="one_on_one_notes",
    )
    op.drop_index(
        op.f("ix_one_on_one_notes_owner_user_id"), table_name="one_on_one_notes"
    )
    op.drop_table("one_on_one_notes")

    op.drop_index("uq_goal_owner_source_external_id", table_name="goals")
    op.drop_column("goals", "target_value")
    op.drop_column("goals", "current_value")
    op.drop_column("goals", "progress")
    op.drop_column("goals", "quarter")
    op.drop_column("goals", "parent_external_id")
    op.drop_column("goals", "goal_type")
    op.drop_column("goals", "external_id")
    op.drop_column("goals", "source")

    op.drop_constraint("uq_users_notion_owner_email", "users", type_="unique")
    op.drop_column("users", "notion_owner_email")
