"""Symmetric encryption for secrets this app must store but never itself
issues (currently: GoogleCredential.refresh_token_encrypted). Distinct
from every other per-user secret in app.core.models — agenda_client_secret
and setup_token are generated by this app and can be freely rotated if
ever exposed; a Google refresh token is a live third-party credential this
app only custodies, so it's encrypted at rest rather than stored plain the
way those are."""

import base64
import os
from functools import lru_cache

from cryptography.fernet import Fernet, InvalidToken

_ENV_VAR = "TOKEN_ENCRYPTION_KEY"


class TokenEncryptionKeyMissing(RuntimeError):
    pass


@lru_cache
def _fernet() -> Fernet:
    raw = os.environ.get(_ENV_VAR)
    if not raw:
        raise TokenEncryptionKeyMissing(
            f"{_ENV_VAR} is not set — refusing to encrypt/decrypt a live "
            "Google credential without it. Generate one with "
            "`python -c \"from cryptography.fernet import Fernet; "
            'print(Fernet.generate_key().decode())"` and set it in .env.'
        )
    # Fernet.generate_key() already returns url-safe-base64 bytes of the
    # right length; validate eagerly here rather than letting a malformed
    # env value surface as a cryptic error on the first real encrypt call.
    try:
        return Fernet(raw.encode())
    except (ValueError, base64.binascii.Error) as exc:
        raise TokenEncryptionKeyMissing(
            f"{_ENV_VAR} is set but not a valid Fernet key"
        ) from exc


def encrypt_token(plaintext: str) -> str:
    return _fernet().encrypt(plaintext.encode()).decode()


def decrypt_token(ciphertext: str) -> str:
    try:
        return _fernet().decrypt(ciphertext.encode()).decode()
    except InvalidToken as exc:
        raise ValueError(
            "stored token could not be decrypted — TOKEN_ENCRYPTION_KEY "
            "may have changed since it was written"
        ) from exc
